### ISSUE TITLE
Suggestion Thread

### ISSUE THREAD

**Issue by NightScale5755** [TeamLapen/Werewolves#10]
Heyo, 
Delete/close this if you will, but I just thought this could be useful.

**Comment by NightScale5755** [comment]
Werewolf Packs; Wild werewolves/dire wolves can be integrated into a player's pack, and have their own level. I.e. you cannot integrate a werewolf with a level higher than yours. The player's pack can only be as big as their level/skills allow. And perhaps even have them have a "happiness meter" So that the player's pack has to hunt, or an alpha battle would occur???
I'm suggesting this, as werewolves are portrayed as hunting in packs...

Also, perhaps a "Werewolf Haven" Biome??? To be the equivalent of the Vampire Forest. It could be some kind of forest, with an increased spawn rate of werewolves, and no silver ore/wolfsbane spawning there? And possibly increased werewolf stats within the biome? For appearance of the Werewolf Haven Biome, I'm thinking something like a fantasy forest? With medium sized trees? And flowers?

An aesthetic example would be the Mystic Grove, from Biomes O Plenty

**Comment by Cheaterpaul** [comment]
1. the idea is good but i would probably implement is later on (if i do it) eventually by implementing such a thing in Vampirism and using is here

2. great idea added a new issue for that https://github.com/TeamLapen/Werewolves/issues/11

**Comment by NightScale5755** [comment]
sooo.. I have another suggestion.
Maybe some smaller buffs for the human form? Like simple skills that only werewolves can have????  With large cooldowns?
Therefore they're not useless when the fullmoon isn't out...

**Comment by NightScale5755** [comment]
hey. It's been a while since I've suggested something.
Here's a thought:
I noticed you plan on allowing hunters to see if players/entities are werewolves.. Why not use something called a "Moon amulet"?
Essentially an item that's used to buff werewolves, yet hunters can purify it with silver, allowing it to be used to detect werewolves?

**Comment by hugo-pinango** [comment]
hello I have an idea to avoid having cd in the transformation or implement it in a similar way to vampirism to transform you need lunar energy that sun you get at night and you can create fracos and accumulate it and with a necklace use it like this transform yourself for as long as you want while you have lunar energy on a full moon, you would not have to use that energy because the moon would give you the transformation all night, also create the version of the counts as alphas in the werewolf biome from 1 to 5 and they give you fangs to use them in the level up also use a player classification as omega until he gets a handle that gives him more power or only gives him the ability to call them I think it would be good or a wolf armor that works as a human and as a wolf (pd: sorry for my bad english)
