### ISSUE TITLE
[Bug]: crashes in forge-bukkit hybrid server

### ISSUE THREAD

**Issue by shlffv** [TeamLapen/Werewolves#105]
### Minecraft Version

1.18.x

### Forge Version

40.1.25

### Vampirism Version

1.8.2

### Werewolves Version

0.6.1

### Singleplayer/Multiplayer

Server

### What happened?

i'm using arclight as server core, and manually updated server forge to 40.1.25. 
after we played for a while, it seems to crash more frequently. 
the werewolf appears in the firstline of the crash report, so i think perhaps werewolf caused server crashes.
i've allowed the permissions werewolves and vampirism required

[crash-2022-05-26_23.45.49-server.txt](https://github.com/TeamLapen/Werewolves/files/8783080/crash-2022-05-26_23.45.49-server.txt)
it seems i can't paste the whole crash report below

here's the plugins
-BetterSleeping-2.6.1
-EssentialsX-2.19.4
-EssentialsX-2.20.0-dev+6-ea5cdc0
-EssentialsXChat-2.20.0-dev+6-ea5cdc0
-LaggRemover-2.0.6
-LuckPerms-Bukkit-5.3.47
-NoSpawnChunks
-PlayerWarps 6.16.0
-Vault

### Relevant log output

```bash
https://github.com/TeamLapen/Werewolves/files/8783080/crash-2022-05-26_23.45.49-server.txt
```

**Comment by Cheaterpaul** [comment]
This is caused by bukkit/arclight not sure what is responsible. I have taken a look at their source code but couldn't figure out how/why this is caused.

From my side it does not look like Werewolves does anything wrong.

I suggest you report this to the Arclight (or Bukkit) issue tracker because they have a much faster way of finding the issue.
