### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by TheRebelT** [TeamLapen/Werewolves#23]
## What would you like to have changed or added to Werewolves
Not much a feature request but a question, I've noticed from the twitter that you're using DrZark's Werewolf model and texture, is this only temporary or are you using it and if you are, did you get permission from him?

## Can you provide additional resources (etc. textures or models)
If assets such as texture sprites and models are an issue, I'd be willing to help out, I can send you screenshots of my work if you're interested.

**Comment by TheRebelT** [comment]
And I'm guessing it adds labels automatically as I don't remember adding one, if not my apologies for that

**Comment by Cheaterpaul** [comment]
I had used it at the beginning to test it. But because Mo' creatures has no license (all right reserved) i replaced it with a blocky  model of my own, because i'm not good at it. [model](https://github.com/TeamLapen/Werewolves/blob/1.14/dev_resources/model/werewolf.bbmodel)(for blockbench)


Yes i would be interested.

**Comment by TheRebelT** [comment]
Where would you like me to send them? If you've got discord, my account is RebelT#6115
