### ISSUE TITLE
[Feature] 1.12.2 Port

### ISSUE THREAD

**Issue by nomoemptypointer** [TeamLapen/Werewolves#45]
We want an 1.12.2 port, because 1.12.2 is best for mods atm, i really like your work made in this, can you make one or you cant? (no idea if porting from 1.16 to 1.12 is hard, and i cannot port it)

**Comment by lunofe** [comment]
There has been a 1.12 version, however it has been abandoned.
![image](https://user-images.githubusercontent.com/42828197/118945376-afef8200-b955-11eb-85a3-fe083432df6f.png)

**Comment by Cheaterpaul** [comment]
As Zinalco mentioned i started with 1.12 but abandoned it because Minecraft/Forge and/or Vampirism did not provide the necessary features for this mod to work.

And since 1.12 is out of date and i have no time i will not port this mod to 1.12. Everyone else is free to do so since it is licensed under LGPL-3.0
